# escape=`
FROM sitecore:8.2.180406-windowsservercore-1803

RUN Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Sitecore.Analytics.Processing.Aggregation.Services.config' -NewName 'Sitecore.Analytics.Processing.Aggregation.Services.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Sitecore.Analytics.Processing.Services.config' -NewName 'Sitecore.Analytics.Processing.Services.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Sitecore.Analytics.Tracking.Aggregation.config' -NewName 'Sitecore.Analytics.Tracking.Aggregation.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Sitecore.Analytics.Tracking.Database.config' -NewName 'Sitecore.Analytics.Tracking.Database.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Sitecore.Analytics.Tracking.RobotDetection.config' -NewName 'Sitecore.Analytics.Tracking.RobotDetection.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Sitecore.ContentSearch.Lucene.Indexes.Sharded.Core.config.example' -NewName 'Sitecore.ContentSearch.Lucene.Indexes.Sharded.Core.config.example.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Sitecore.ContentSearch.Lucene.Indexes.Sharded.Master.config.example' -NewName 'Sitecore.ContentSearch.Lucene.Indexes.Sharded.Master.config.example.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Sitecore.ContentSearch.Lucene.Indexes.Sharded.Web.config.example' -NewName 'Sitecore.ContentSearch.Lucene.Indexes.Sharded.Web.config.example.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Sitecore.EngagementAutomation.Processing.Aggregation.Services.config' -NewName 'Sitecore.EngagementAutomation.Processing.Aggregation.Services.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Sitecore.PathAnalyzer.Processing.config' -NewName 'Sitecore.PathAnalyzer.Processing.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Sitecore.PathAnalyzer.RemoteClient.config.disabled' -NewName 'Sitecore.PathAnalyzer.RemoteClient.config'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Sitecore.Xdb.Remote.Client.config.disabled' -NewName 'Sitecore.Xdb.Remote.Client.config'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Sitecore.Xdb.Remote.Client.MarketingAssets.config.disabled' -NewName 'Sitecore.Xdb.Remote.Client.MarketingAssets.config'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\ContentTesting\Sitecore.ContentTesting.PreemptiveScreenshot.config.disabled' -NewName 'Sitecore.ContentTesting.PreemptiveScreenshot.config'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\ContentTesting\Sitecore.ContentTesting.Processing.Aggregation.config' -NewName 'Sitecore.ContentTesting.Processing.Aggregation.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\ExperienceAnalytics\Sitecore.ExperienceAnalytics.Aggregation.config' -NewName 'Sitecore.ExperienceAnalytics.Aggregation.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\ExperienceAnalytics\Sitecore.ExperienceAnalytics.Reduce.config' -NewName 'Sitecore.ExperienceAnalytics.Reduce.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\ListManagement\Sitecore.ListManagement.DisableListLocking.config.disabled' -NewName 'Sitecore.ListManagement.DisableListLocking.config'; `
    Rename-Item -Path 'C:\Sitecore\website\App_Config\Include\Social\Sitecore.Social.ScalabilitySettings.config.disabled' -NewName 'Sitecore.Social.ScalabilitySettings.config'; `
    Rename-Item -Path 'C:\Sitecore\website\sitecore\shell\Applications\Reports\Dashboard\CampaignCategoryDefaultSettings.config' -NewName 'CampaignCategoryDefaultSettings.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\sitecore\shell\Applications\Reports\Dashboard\Configuration.config' -NewName 'Configuration.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\sitecore\shell\Applications\Reports\Dashboard\DefaultSettings.config' -NewName 'DefaultSettings.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\sitecore\shell\Applications\Reports\Dashboard\SingleCampaignDefaultSettings.config' -NewName 'SingleCampaignDefaultSettings.config.disabled'; `
    Rename-Item -Path 'C:\Sitecore\website\sitecore\shell\Applications\Reports\Dashboard\SingleTrafficTypeDefaultSettings.config' -NewName 'SingleTrafficTypeDefaultSettings.config.disabled'